# This is the recommended way of running Baserow using docker-compose for most users.
# See https://baserow.io/docs/installation%2Finstall-with-docker for more details.
version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.30.1
    environment:
      BASEROW_PUBLIC_URL: 'http://localhost'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data:
