apiVersion: v2
name: baserow
description: The open platform to create scalable databases and applicationsâ€”without coding.
type: application
version: 1.0.12
appVersion: "1.30.1"
home: https://gitlab.com/baserow/baserow/-/tree/develop/deploy/helm/baserow?ref_type=heads
icon: https://baserow.io/img/favicon_192.png
sources:
  - https://gitlab.com/baserow/baserow
  - https://baserow.io

dependencies:
  - name: baserow
    alias: baserow-backend-asgi
    version: "1.0.12"
    repository: "file://charts/baserow-common"

  - name: baserow
    alias: baserow-backend-wsgi
    version: "1.0.12"
    repository: "file://charts/baserow-common"

  - name: baserow
    alias: baserow-frontend
    version: "1.0.12"
    repository: "file://charts/baserow-common"

  - name: baserow
    alias: baserow-celery-beat-worker
    version: "1.0.12"
    repository: "file://charts/baserow-common"

  - name: baserow
    alias: baserow-celery-export-worker
    version: "1.0.12"
    repository: "file://charts/baserow-common"

  - name: baserow
    alias: baserow-celery-worker
    version: "1.0.12"
    repository: "file://charts/baserow-common"

  - name: baserow
    alias: baserow-celery-flower
    version: "1.0.12"
    repository: "file://charts/baserow-common"
    condition: baserow-celery-flower.enabled

  - name: redis
    version: 19.5.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: postgresql
    version: 15.5.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: minio
    version: 14.6.18
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled

  - name: caddy-ingress-controller
    alias: caddy
    version: 1.1.0
    repository: https://caddyserver.github.io/ingress
    condition: caddy.enabled

annotations:
  artifacthub.io/category: database
  artifacthub.io/keywords: baserow, database, application, scalable, open-source
  artifacthub.io/links: |
    - name: website
      url: https://baserow.io
    - name: source
      url: https://gitlab.com/baserow/baserow
    - name: helm
      url: https://gitlab.com/baserow/baserow/-/tree/develop/deploy/helm/baserow?ref_type=heads
  artifacthub.io/quality: production
