{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "baserow.global.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.baserow.backendDomain | default (printf "api.%s" .Values.global.baserow.domain) }}
      http:
        paths:
          - path: /ws/
            pathType: Prefix
            backend:
              service:
                name: {{ include "baserow.global.fullname" . }}-baserow-backend-asgi
                port:
                  number: 80
          - path: /mcp/
            pathType: Prefix
            backend:
              service:
                name: {{ include "baserow.global.fullname" . }}-baserow-backend-asgi
                port:
                  number: 80
          - path: /assistant/
            pathType: Prefix
            backend:
              service:
                name: {{ include "baserow.global.fullname" . }}-baserow-backend-asgi
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "baserow.global.fullname" . }}-baserow-backend-wsgi
                port:
                  number: 80
    - host: {{ .Values.global.baserow.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "baserow.global.fullname" . }}-baserow-frontend
                port:
                  number: 80
    {{- if .Values.minio.enabled }}
    - host: {{ .Values.global.baserow.objectsDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "common.names.fullname" .Subcharts.minio }}
                port:
                  number: 9000
    {{- end }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "baserow.global.fullname" . }}-baserow-frontend
                port:
                  number: 80
  {{- if .Values.ingress.tls }}
  tls:
    {{ tpl (toYaml .Values.ingress.tls | indent 4) . }}
  {{- end -}}
{{ end }}
