version: "3.4"

services:

  backend:
    image: ${BACKEND_CI_DEV_IMAGE:-baserow_backend_dev:latest}
    environment:
      SECRET_KEY: test
      PUBLIC_BACKEND_URL: http://backend:8000
      PUBLIC_WEB_FRONTEND_URL: http://web-frontend:3000
      BASEROW_AMOUNT_OF_WORKERS: 2
      BASEROW_TRIGGER_SYNC_TEMPLATES_AFTER_MIGRATION: false
      DJANGO_SETTINGS_MODULE: 'baserow.config.settings.base'
    command:
      - gunicorn

  web-frontend:
    image: ${WEBFRONTEND_CI_DEV_IMAGE:-baserow_web-frontend_dev:latest}
    environment:
      PUBLIC_BACKEND_URL: http://backend:8000
      PUBLIC_WEB_FRONTEND_URL: http://web-frontend:3000
    command:
      - nuxt-dev-no-attach

  celery:
    image: ${BACKEND_CI_DEV_IMAGE:-baserow_backend_dev:latest}
    environment:
      BASEROW_RUN_MINIMAL: 'yes'
      BASEROW_AMOUNT_OF_WORKERS: 1
      SECRET_KEY: test
    command: celery-worker

  e2e-tests:
    image: ${E2E_TEST_IMAGE:-baserow_e2e-tests:latest}
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      PUBLIC_BACKEND_URL: http://backend:8000
      PUBLIC_WEB_FRONTEND_URL: http://web-frontend:3000
      CI: 1
      DEBUG: "pw:api"
    depends_on:
      - backend
      - web-frontend
    volumes:
      - /baserow/e2e-tests/node_modules
      - $PWD:/baserow/e2e-tests
    command: "bash -c './wait-for-services.sh && yarn run ${E2E_TEST_YARN_RUN_CMD:-test}'"
    stdin_open: true
    tty: true

  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow
      - POSTGRES_DB=baserow

  redis:
    image: redis:6
